import * as fs from "fs";
import * as path from "path";

// Read .env.local directly to avoid shell parsing issues
const envPath = path.resolve(__dirname, "..", ".env.local");
const envContent = fs.readFileSync(envPath, "utf-8");
const envVars: Record<string, string> = {};
for (const line of envContent.split("\n")) {
  const match = line.match(/^([^=]+)=(.*)$/);
  if (match) envVars[match[1].trim()] = match[2].trim();
}

const NOTION_TOKEN = envVars.NOTION_TOKEN || process.env.NOTION_TOKEN!;
const databaseId = envVars.NOTION_DEALS_DATABASE_ID || process.env.NOTION_DEALS_DATABASE_ID!;

console.log(`Token starts with: ${NOTION_TOKEN.substring(0, 10)}...`);
console.log(`Database ID: ${databaseId}`);

const notionHeaders = {
  Authorization: `Bearer ${NOTION_TOKEN}`,
  "Notion-Version": "2022-06-28",
  "Content-Type": "application/json",
};

async function notionCreatePage(body: any): Promise<any> {
  const res = await fetch("https://api.notion.com/v1/pages", {
    method: "POST",
    headers: notionHeaders,
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(err.message || `HTTP ${res.status}`);
  }
  return res.json();
}

interface Deal {
  slug: string;
  name: string;
  logo: string;
  category: string;
  audiences: string[];
  tagline: string;
  description: string;
  value: string;
  steps: string;
  url: string;
  featured: boolean;
}

const newDeals: Deal[] = [
  // ===== DEV (20) =====
  {
    slug: "gitkraken",
    name: "GitKraken",
    logo: "/logos/gitkraken.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free Pro suite for students",
    description: "GitKraken offers its Pro suite free for students via the GitHub Student Developer Pack. Includes GitKraken Client, GitLens Pro, and more.",
    value: "$108/year",
    steps: "Sign up for GitHub Student Developer Pack\nRedeem GitKraken Pro via the pack\nDownload and log in with your GitHub account",
    url: "https://www.gitkraken.com/github-student-developer-pack",
    featured: false,
  },
  {
    slug: "termius",
    name: "Termius",
    logo: "/logos/termius.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free Premium SSH client for students",
    description: "Termius Premium is free for students through the GitHub Student Developer Pack. Sync SSH sessions across devices with encrypted vault.",
    value: "$120/year",
    steps: "Get GitHub Student Developer Pack\nRedeem Termius Premium from partner offers\nInstall Termius and sync across devices",
    url: "https://termius.com/education",
    featured: false,
  },
  {
    slug: "popsql",
    name: "PopSQL",
    logo: "/logos/popsql.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free Premium SQL editor for students",
    description: "PopSQL offers its Premium plan free for students. Collaborative SQL editor with shared queries, charts, and database connections.",
    value: "$228/year",
    steps: "Sign up at popsql.com\nVerify student status with .edu email\nGet Premium plan activated",
    url: "https://popsql.com/pricing",
    featured: false,
  },
  {
    slug: "tower-git",
    name: "Tower Git",
    logo: "/logos/tower-git.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free Git client license for students",
    description: "Tower offers free licenses for students. A powerful Git client for Mac and Windows with visual branch management and conflict resolution.",
    value: "$69/year",
    steps: "Go to git-tower.com/students\nApply with your .edu email\nReceive free license key via email",
    url: "https://www.git-tower.com/students/",
    featured: false,
  },
  {
    slug: "codacy",
    name: "Codacy",
    logo: "/logos/codacy.svg",
    category: "Dev",
    audiences: ["Opensource"],
    tagline: "Free code quality for open source",
    description: "Codacy provides free automated code review and quality analysis for open source projects. Supports 40+ languages.",
    value: "Free tier",
    steps: "Sign up at codacy.com\nConnect your open source repository\nGet automated code reviews on every commit",
    url: "https://www.codacy.com/pricing",
    featured: false,
  },
  {
    slug: "travis-ci",
    name: "Travis CI",
    logo: "/logos/travis-ci.svg",
    category: "Dev",
    audiences: ["Opensource"],
    tagline: "Free CI/CD for open source projects",
    description: "Travis CI offers free continuous integration for open source projects on GitHub. Automated testing across multiple environments.",
    value: "Free tier",
    steps: "Sign up with your GitHub account\nAdd .travis.yml to your OSS repo\nGet automated builds on every push",
    url: "https://www.travis-ci.com/",
    featured: false,
  },
  {
    slug: "circleci",
    name: "CircleCI",
    logo: "/logos/circleci.svg",
    category: "Dev",
    audiences: ["Opensource", "Startups"],
    tagline: "Free CI/CD plan for OSS and startups",
    description: "CircleCI provides generous free tier with 6,000 build minutes/month. Additional credits for open source projects.",
    value: "6,000 min/month",
    steps: "Sign up at circleci.com with GitHub\nAdd .circleci/config.yml to your repo\nGet automated builds for free",
    url: "https://circleci.com/pricing/",
    featured: false,
  },
  {
    slug: "gitlab-education",
    name: "GitLab for Education",
    logo: "/logos/gitlab.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free Ultimate plan for students",
    description: "GitLab offers its Ultimate plan free for qualified educational institutions and students. Includes all DevOps features.",
    value: "$1,188/year",
    steps: "Go to about.gitlab.com/solutions/education\nApply with your institution details\nGet GitLab Ultimate activated",
    url: "https://about.gitlab.com/solutions/education/",
    featured: true,
  },
  {
    slug: "bitbucket-education",
    name: "Bitbucket",
    logo: "/logos/bitbucket.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free unlimited private repos for students",
    description: "Bitbucket offers free academic licenses with unlimited private repositories and CI/CD minutes for students and educators.",
    value: "Free tier",
    steps: "Create an Atlassian account\nApply at bitbucket.org/product/education\nGet unlimited private repos",
    url: "https://bitbucket.org/product/education",
    featured: false,
  },
  {
    slug: "postman-students",
    name: "Postman",
    logo: "/logos/postman.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free Basic plan for students",
    description: "Postman offers free access to its Basic plan features for students through the GitHub Student Developer Pack.",
    value: "$144/year",
    steps: "Get GitHub Student Developer Pack\nRedeem Postman access from partner offers\nSign in and start testing APIs",
    url: "https://www.postman.com/student-program/",
    featured: false,
  },
  {
    slug: "insomnia",
    name: "Insomnia",
    logo: "/logos/insomnia.svg",
    category: "Dev",
    audiences: ["Opensource"],
    tagline: "Free open source API client",
    description: "Insomnia is a free, open source API client for REST, GraphQL, and gRPC. Design, debug, and test APIs with ease.",
    value: "Free",
    steps: "Download Insomnia from insomnia.rest\nImport your API specs\nStart testing and debugging APIs",
    url: "https://insomnia.rest/",
    featured: false,
  },
  {
    slug: "tableplus",
    name: "TablePlus",
    logo: "/logos/tableplus.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Discounted license for students",
    description: "TablePlus offers student discounts on its native database management tool. Supports MySQL, PostgreSQL, SQLite, and more.",
    value: "50% off",
    steps: "Go to tableplus.com/education\nVerify student status\nGet discounted license",
    url: "https://tableplus.com/",
    featured: false,
  },
  {
    slug: "datagrip-students",
    name: "DataGrip",
    logo: "/logos/datagrip.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free database IDE for students",
    description: "DataGrip by JetBrains is free for students. Professional database IDE supporting multiple databases with intelligent query editing.",
    value: "$229/year",
    steps: "Apply at jetbrains.com/student\nVerify with .edu email or ISIC card\nDownload DataGrip from JetBrains Toolbox",
    url: "https://www.jetbrains.com/datagrip/",
    featured: false,
  },
  {
    slug: "visual-studio-enterprise",
    name: "Visual Studio Enterprise",
    logo: "/logos/visual-studio.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free Visual Studio Enterprise for students",
    description: "Microsoft offers Visual Studio Enterprise free through Azure Dev Tools for Teaching. Full IDE with advanced debugging and testing tools.",
    value: "$5,999/year",
    steps: "Go to Azure Dev Tools for Teaching\nSign in with your school account\nDownload Visual Studio Enterprise",
    url: "https://visualstudio.microsoft.com/free-developer-offers/",
    featured: true,
  },
  {
    slug: "unity-student",
    name: "Unity Student",
    logo: "/logos/unity.svg",
    category: "Dev",
    audiences: ["Students"],
    tagline: "Free Unity Pro license for students",
    description: "Unity offers free access to Unity Student plan with Pro features for eligible students. Build games and 3D experiences.",
    value: "$2,040/year",
    steps: "Go to unity.com/products/unity-student\nVerify student status\nDownload Unity Hub and activate license",
    url: "https://unity.com/products/unity-student",
    featured: true,
  },
  {
    slug: "unreal-engine",
    name: "Unreal Engine",
    logo: "/logos/unreal-engine.svg",
    category: "Dev",
    audiences: ["Students", "Opensource"],
    tagline: "Free game engine for students",
    description: "Unreal Engine is free to use for students and learners. No royalties until you ship a commercial product earning over $1M.",
    value: "Free",
    steps: "Create an Epic Games account\nDownload Epic Games Launcher\nInstall Unreal Engine and start building",
    url: "https://www.unrealengine.com/en-US/education",
    featured: false,
  },
  {
    slug: "planetscale",
    name: "PlanetScale",
    logo: "/logos/planetscale.svg",
    category: "Dev",
    audiences: ["Startups", "Opensource"],
    tagline: "Serverless MySQL with free tier",
    description: "PlanetScale offers a serverless MySQL database platform with branching, non-blocking schema changes, and a generous free tier.",
    value: "Free tier",
    steps: "Sign up at planetscale.com\nCreate your first database\nConnect with your favorite framework",
    url: "https://planetscale.com/pricing",
    featured: false,
  },
  {
    slug: "neon-database",
    name: "Neon",
    logo: "/logos/neon.svg",
    category: "Dev",
    audiences: ["Startups", "Opensource"],
    tagline: "Serverless Postgres with generous free tier",
    description: "Neon offers serverless PostgreSQL with autoscaling, branching, and a generous free tier including 0.5 GB storage and 190 compute hours.",
    value: "Free tier",
    steps: "Sign up at neon.tech\nCreate a project and database\nConnect using standard Postgres drivers",
    url: "https://neon.tech/",
    featured: false,
  },
  {
    slug: "turso",
    name: "Turso",
    logo: "/logos/turso.svg",
    category: "Dev",
    audiences: ["Startups", "Opensource"],
    tagline: "Edge SQLite database with free tier",
    description: "Turso provides edge-hosted SQLite databases with a free Starter plan including 500 databases, 9 GB storage, and 25M row reads.",
    value: "Free tier",
    steps: "Sign up at turso.tech\nInstall the Turso CLI\nCreate and deploy your first database",
    url: "https://turso.tech/pricing",
    featured: false,
  },
  {
    slug: "github-actions",
    name: "GitHub Actions",
    logo: "/logos/github.svg",
    category: "Dev",
    audiences: ["Opensource"],
    tagline: "Free CI/CD for public repositories",
    description: "GitHub Actions provides unlimited CI/CD minutes for public repositories. Automate builds, tests, and deployments with YAML workflows.",
    value: "Unlimited for OSS",
    steps: "Create a GitHub repository (public)\nAdd .github/workflows/ YAML files\nPush code to trigger automated pipelines",
    url: "https://github.com/features/actions",
    featured: false,
  },

  // ===== AI (15) =====
  {
    slug: "anthropic-api-credits",
    name: "Anthropic API Credits",
    logo: "/logos/anthropic.svg",
    category: "AI",
    audiences: ["Startups"],
    tagline: "API credits for AI startups",
    description: "Anthropic provides API credits for startups through partner programs like Google Cloud for Startups and AWS Activate.",
    value: "$1,000+ credits",
    steps: "Apply through a partner accelerator program\nGet accepted into the startup program\nReceive Claude API credits",
    url: "https://www.anthropic.com/",
    featured: false,
  },
  {
    slug: "google-cloud-ai",
    name: "Google Cloud AI",
    logo: "/logos/google-cloud.svg",
    category: "AI",
    audiences: ["Startups", "Students"],
    tagline: "AI/ML credits via Google Cloud programs",
    description: "Google Cloud offers AI and ML API credits through its startup and education programs. Access Vertex AI, Gemini API, and more.",
    value: "$2,000+ credits",
    steps: "Apply for Google for Startups Cloud Program\nGet approved for cloud credits\nActivate AI/ML APIs in your project",
    url: "https://cloud.google.com/ai",
    featured: false,
  },
  {
    slug: "huggingface",
    name: "Hugging Face",
    logo: "/logos/huggingface.svg",
    category: "AI",
    audiences: ["Opensource", "Students"],
    tagline: "Free ML model hosting and inference",
    description: "Hugging Face offers free model hosting, datasets, and inference API for open source ML projects. Hub with 500K+ models.",
    value: "Free tier",
    steps: "Create a Hugging Face account\nUpload or use existing models from the Hub\nUse free Inference API or Spaces for hosting",
    url: "https://huggingface.co/",
    featured: false,
  },
  {
    slug: "wandb",
    name: "Weights & Biases",
    logo: "/logos/wandb.svg",
    category: "AI",
    audiences: ["Students", "Opensource"],
    tagline: "Free ML experiment tracking for academics",
    description: "Weights & Biases offers free academic plans for students and researchers. Track ML experiments, visualize results, and collaborate.",
    value: "Free for academics",
    steps: "Sign up at wandb.ai with .edu email\nApply for academic plan\nIntegrate W&B into your ML pipeline",
    url: "https://wandb.ai/site/research",
    featured: false,
  },
  {
    slug: "comet-ml",
    name: "Comet ML",
    logo: "/logos/comet-ml.svg",
    category: "AI",
    audiences: ["Students", "Opensource"],
    tagline: "Free ML platform for academics",
    description: "Comet offers free academic access to its ML experiment management platform. Log, compare, and reproduce ML experiments.",
    value: "Free for academics",
    steps: "Sign up at comet.com\nApply for academic plan with .edu email\nIntegrate Comet SDK into your ML code",
    url: "https://www.comet.com/site/pricing/",
    featured: false,
  },
  {
    slug: "neptune-ai",
    name: "Neptune.ai",
    logo: "/logos/neptune-ai.svg",
    category: "AI",
    audiences: ["Students", "Opensource"],
    tagline: "Free experiment tracker for researchers",
    description: "Neptune.ai provides free plans for individual researchers and open source projects. Track and version ML experiments at scale.",
    value: "Free tier",
    steps: "Sign up at neptune.ai\nGet free Individual plan\nIntegrate Neptune client into your training scripts",
    url: "https://neptune.ai/pricing",
    featured: false,
  },
  {
    slug: "replit",
    name: "Replit",
    logo: "/logos/replit.svg",
    category: "AI",
    audiences: ["Students"],
    tagline: "Free AI-powered coding environment",
    description: "Replit provides a free cloud IDE with AI assistance, collaborative coding, and instant deployment. Build and ship from your browser.",
    value: "Free tier",
    steps: "Sign up at replit.com\nCreate a new Repl in any language\nUse AI assistant to help write code",
    url: "https://replit.com/",
    featured: false,
  },
  {
    slug: "cursor",
    name: "Cursor",
    logo: "/logos/cursor.svg",
    category: "AI",
    audiences: ["Students"],
    tagline: "AI code editor with free tier",
    description: "Cursor is an AI-powered code editor built on VS Code. Free tier includes AI completions and chat. Pro features available for students.",
    value: "Free tier",
    steps: "Download Cursor from cursor.com\nSign in with your account\nStart coding with AI completions and chat",
    url: "https://www.cursor.com/",
    featured: false,
  },
  {
    slug: "tabnine",
    name: "Tabnine",
    logo: "/logos/tabnine.svg",
    category: "AI",
    audiences: ["Students"],
    tagline: "Free AI code completion for students",
    description: "Tabnine offers free Pro-level AI code completion for students. Works in all major IDEs with privacy-focused AI models.",
    value: "$144/year",
    steps: "Sign up at tabnine.com\nApply for student plan with .edu email\nInstall the Tabnine plugin in your IDE",
    url: "https://www.tabnine.com/students",
    featured: false,
  },
  {
    slug: "codeium",
    name: "Codeium",
    logo: "/logos/codeium.svg",
    category: "AI",
    audiences: ["Students", "Opensource"],
    tagline: "Free AI code completion for everyone",
    description: "Codeium provides free AI-powered code completion and chat for individual developers. Supports 70+ languages and 40+ editors.",
    value: "Free",
    steps: "Sign up at codeium.com\nInstall the extension in your IDE\nStart getting AI-powered completions",
    url: "https://codeium.com/",
    featured: false,
  },
  {
    slug: "deepl-pro",
    name: "DeepL Pro",
    logo: "/logos/deepl.svg",
    category: "AI",
    audiences: ["Startups"],
    tagline: "Discounted translation API for startups",
    description: "DeepL offers startup programs with discounted access to its AI translation API. Support for 30+ languages with high accuracy.",
    value: "Startup pricing",
    steps: "Visit deepl.com/pro\nContact sales for startup pricing\nIntegrate DeepL API into your product",
    url: "https://www.deepl.com/pro",
    featured: false,
  },
  {
    slug: "grammarly-students",
    name: "Grammarly",
    logo: "/logos/grammarly.svg",
    category: "AI",
    audiences: ["Students"],
    tagline: "Discounted Premium for students",
    description: "Grammarly offers discounted Premium plans for students. AI-powered writing assistant with grammar, style, and plagiarism checking.",
    value: "40% off",
    steps: "Visit grammarly.com/edu\nVerify student status\nGet discounted Premium subscription",
    url: "https://www.grammarly.com/edu",
    featured: false,
  },
  {
    slug: "jasper-ai",
    name: "Jasper AI",
    logo: "/logos/jasper.svg",
    category: "AI",
    audiences: ["Startups"],
    tagline: "AI content platform for startups",
    description: "Jasper offers startup-friendly pricing for its AI content creation platform. Generate marketing copy, blog posts, and more.",
    value: "Startup pricing",
    steps: "Visit jasper.ai\nContact sales for startup pricing\nStart creating AI-generated content",
    url: "https://www.jasper.ai/",
    featured: false,
  },
  {
    slug: "replicate",
    name: "Replicate",
    logo: "/logos/replicate.svg",
    category: "AI",
    audiences: ["Opensource", "Startups"],
    tagline: "Run ML models with free tier",
    description: "Replicate lets you run open source ML models in the cloud with a simple API. Free tier for getting started.",
    value: "Free tier",
    steps: "Sign up at replicate.com\nBrowse and pick an ML model\nRun predictions via API or web interface",
    url: "https://replicate.com/pricing",
    featured: false,
  },
  {
    slug: "kaggle",
    name: "Kaggle",
    logo: "/logos/kaggle.svg",
    category: "AI",
    audiences: ["Students", "Opensource"],
    tagline: "Free GPUs and ML competitions",
    description: "Kaggle provides free GPU/TPU notebooks, datasets, competitions, and courses. Learn ML and compete for prizes.",
    value: "Free",
    steps: "Sign up at kaggle.com\nExplore datasets and competitions\nUse free GPU notebooks for training",
    url: "https://www.kaggle.com/",
    featured: false,
  },

  // ===== CLOUD (15) =====
  {
    slug: "google-cloud-startups",
    name: "Google Cloud for Startups",
    logo: "/logos/google-cloud.svg",
    category: "Cloud",
    audiences: ["Startups"],
    tagline: "Up to $200K in Google Cloud credits",
    description: "Google for Startups Cloud Program offers up to $200K in cloud credits, technical training, and business support for eligible startups.",
    value: "$200,000",
    steps: "Apply at cloud.google.com/startup\nProvide your startup details and funding info\nGet approved for up to $200K in credits",
    url: "https://cloud.google.com/startup",
    featured: true,
  },
  {
    slug: "hetzner",
    name: "Hetzner",
    logo: "/logos/hetzner.svg",
    category: "Cloud",
    audiences: ["Startups", "Opensource"],
    tagline: "Affordable European cloud hosting",
    description: "Hetzner offers some of the most affordable cloud servers in Europe. CX11 cloud server starting at under $5/month with German data centers.",
    value: "Low-cost cloud",
    steps: "Sign up at hetzner.com\nCreate a cloud project\nDeploy servers from EUR 3.79/month",
    url: "https://www.hetzner.com/cloud/",
    featured: false,
  },
  {
    slug: "linode-akamai",
    name: "Linode (Akamai)",
    logo: "/logos/linode.svg",
    category: "Cloud",
    audiences: ["Startups"],
    tagline: "$100 free credit for new users",
    description: "Linode (now Akamai Connected Cloud) offers $100 in free credit for 60 days for new users. Simple, affordable cloud computing.",
    value: "$100 credit",
    steps: "Sign up at linode.com\nGet $100 free credit automatically\nDeploy cloud instances and services",
    url: "https://www.linode.com/",
    featured: false,
  },
  {
    slug: "vultr",
    name: "Vultr",
    logo: "/logos/vultr.svg",
    category: "Cloud",
    audiences: ["Startups"],
    tagline: "$250 free credit for new accounts",
    description: "Vultr provides $250 in free credit for 30 days for new accounts. High-performance cloud compute, storage, and networking.",
    value: "$250 credit",
    steps: "Sign up at vultr.com\nGet $250 free credit automatically\nDeploy cloud servers in 32+ locations",
    url: "https://www.vultr.com/",
    featured: false,
  },
  {
    slug: "render",
    name: "Render",
    logo: "/logos/render.svg",
    category: "Cloud",
    audiences: ["Startups", "Opensource"],
    tagline: "Free tier for web services and databases",
    description: "Render offers free static site hosting, web services, and PostgreSQL databases. Easy deployment from Git with auto-scaling.",
    value: "Free tier",
    steps: "Sign up at render.com\nConnect your GitHub repository\nDeploy web services for free",
    url: "https://render.com/pricing",
    featured: false,
  },
  {
    slug: "fly-io",
    name: "Fly.io",
    logo: "/logos/fly-io.svg",
    category: "Cloud",
    audiences: ["Startups", "Opensource"],
    tagline: "Free tier with global edge deployment",
    description: "Fly.io offers free tier including 3 shared VMs, 3 GB storage, and 160 GB bandwidth. Deploy apps to edge locations worldwide.",
    value: "Free tier",
    steps: "Install the flyctl CLI\nSign up at fly.io\nDeploy your app to global edge network",
    url: "https://fly.io/pricing/",
    featured: false,
  },
  {
    slug: "netlify",
    name: "Netlify",
    logo: "/logos/netlify.svg",
    category: "Cloud",
    audiences: ["Opensource", "Startups"],
    tagline: "Free hosting for static sites and functions",
    description: "Netlify offers a generous free tier with 100 GB bandwidth, 300 build minutes, and serverless functions. Open source projects get Pro for free.",
    value: "Free tier",
    steps: "Sign up at netlify.com\nConnect your Git repository\nDeploy with automatic builds on every push",
    url: "https://www.netlify.com/pricing/",
    featured: false,
  },
  {
    slug: "heroku-students",
    name: "Heroku",
    logo: "/logos/heroku.svg",
    category: "Cloud",
    audiences: ["Students"],
    tagline: "Platform credits via GitHub Education",
    description: "Heroku offers platform credits for students through the GitHub Student Developer Pack. Deploy apps with managed infrastructure.",
    value: "$156 credits",
    steps: "Get GitHub Student Developer Pack\nRedeem Heroku credits from partner offers\nDeploy your app on Heroku",
    url: "https://www.heroku.com/students",
    featured: false,
  },
  {
    slug: "ibm-cloud",
    name: "IBM Cloud",
    logo: "/logos/ibm-cloud.svg",
    category: "Cloud",
    audiences: ["Students", "Startups"],
    tagline: "Free Lite tier with 40+ services",
    description: "IBM Cloud offers a free Lite tier with 40+ always-free services including Watson AI, Cloud Functions, and Kubernetes.",
    value: "Free tier",
    steps: "Sign up at cloud.ibm.com\nExplore Lite plan services\nBuild with Watson AI and cloud services",
    url: "https://www.ibm.com/cloud/free",
    featured: false,
  },
  {
    slug: "oracle-cloud",
    name: "Oracle Cloud",
    logo: "/logos/oracle-cloud.svg",
    category: "Cloud",
    audiences: ["Startups", "Students"],
    tagline: "Always Free tier with generous resources",
    description: "Oracle Cloud offers an Always Free tier including 2 AMD VMs, 4 Arm VMs, 200 GB storage, and 10 TB bandwidth per month.",
    value: "Always Free",
    steps: "Sign up at cloud.oracle.com\nActivate Always Free resources\nDeploy VMs and databases at no cost",
    url: "https://www.oracle.com/cloud/free/",
    featured: false,
  },
  {
    slug: "alibaba-cloud",
    name: "Alibaba Cloud",
    logo: "/logos/alibaba-cloud.svg",
    category: "Cloud",
    audiences: ["Startups"],
    tagline: "Startup credits up to $120K",
    description: "Alibaba Cloud offers up to $120K in credits for eligible startups. Global infrastructure with competitive pricing.",
    value: "$120,000 credits",
    steps: "Apply at alibabacloud.com/startups\nSubmit your startup details\nGet approved for cloud credits",
    url: "https://www.alibabacloud.com/startup",
    featured: false,
  },
  {
    slug: "scaleway",
    name: "Scaleway",
    logo: "/logos/scaleway.svg",
    category: "Cloud",
    audiences: ["Startups"],
    tagline: "European cloud with startup program",
    description: "Scaleway offers a startup program with cloud credits and technical support. European cloud with compute, storage, and AI services.",
    value: "Startup credits",
    steps: "Apply at scaleway.com/startups\nDescribe your startup and needs\nGet approved for credits and support",
    url: "https://www.scaleway.com/en/startup-program/",
    featured: false,
  },
  {
    slug: "back4app",
    name: "Back4App",
    logo: "/logos/back4app.svg",
    category: "Cloud",
    audiences: ["Students", "Startups"],
    tagline: "Free Backend-as-a-Service tier",
    description: "Back4App offers a free tier with 25K API requests/month based on Parse Platform. Simple backend for mobile and web apps.",
    value: "Free tier",
    steps: "Sign up at back4app.com\nCreate a new app\nUse Parse SDKs to build your backend",
    url: "https://www.back4app.com/pricing",
    featured: false,
  },
  {
    slug: "firebase",
    name: "Firebase",
    logo: "/logos/firebase.svg",
    category: "Cloud",
    audiences: ["Students", "Startups"],
    tagline: "Generous free Spark plan by Google",
    description: "Firebase Spark plan is free forever with authentication, Firestore, hosting, cloud functions, and more. Full BaaS by Google.",
    value: "Free tier",
    steps: "Go to firebase.google.com\nCreate a project\nAdd Firebase SDK to your app",
    url: "https://firebase.google.com/pricing",
    featured: false,
  },
  {
    slug: "azure-students",
    name: "Microsoft Azure for Students",
    logo: "/logos/azure.svg",
    category: "Cloud",
    audiences: ["Students"],
    tagline: "$100 Azure credits without credit card",
    description: "Microsoft Azure for Students gives $100 in credits without requiring a credit card. Access 25+ free services including VMs and AI.",
    value: "$100 credits",
    steps: "Go to azure.microsoft.com/free/students\nSign in with your school email\nGet $100 credit and free services",
    url: "https://azure.microsoft.com/en-us/free/students/",
    featured: true,
  },

  // ===== SaaS (15) =====
  {
    slug: "airtable",
    name: "Airtable",
    logo: "/logos/airtable.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Free tier for small teams",
    description: "Airtable offers a free tier with unlimited bases, 1,000 records per base, and 1 GB attachments. Perfect for startup operations.",
    value: "Free tier",
    steps: "Sign up at airtable.com\nCreate your first base\nBuild workflows with views and automations",
    url: "https://airtable.com/pricing",
    featured: false,
  },
  {
    slug: "asana-startups",
    name: "Asana",
    logo: "/logos/asana.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Free Basic plan for small teams",
    description: "Asana offers a free Basic plan for teams up to 10 members. Project management with tasks, timelines, and integrations.",
    value: "Free tier",
    steps: "Sign up at asana.com\nCreate a workspace for your startup\nStart managing projects with your team",
    url: "https://asana.com/pricing",
    featured: false,
  },
  {
    slug: "monday-startups",
    name: "Monday.com",
    logo: "/logos/monday.svg",
    category: "SaaS",
    audiences: ["Startups", "Students"],
    tagline: "Free plan for students and small teams",
    description: "Monday.com offers a free Individual plan and startup program. Work management platform with boards, automations, and integrations.",
    value: "Free tier",
    steps: "Sign up at monday.com\nCreate your first board\nInvite team members and track work",
    url: "https://monday.com/pricing",
    featured: false,
  },
  {
    slug: "clickup",
    name: "ClickUp",
    logo: "/logos/clickup.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Free plan with unlimited tasks",
    description: "ClickUp offers a free Forever plan with unlimited tasks, members, and 100 MB storage. All-in-one productivity platform.",
    value: "Free tier",
    steps: "Sign up at clickup.com\nCreate a workspace\nOrganize tasks with lists, boards, and docs",
    url: "https://clickup.com/pricing",
    featured: false,
  },
  {
    slug: "intercom-startups",
    name: "Intercom",
    logo: "/logos/intercom.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "95% off for early-stage startups",
    description: "Intercom offers 95% discount for early-stage startups through their Early Stage program. Customer messaging platform with chat, bots, and help center.",
    value: "95% off first year",
    steps: "Apply at intercom.com/early-stage\nProvide your startup details and funding stage\nGet approved for 95% discount",
    url: "https://www.intercom.com/early-stage",
    featured: true,
  },
  {
    slug: "zendesk-startups",
    name: "Zendesk for Startups",
    logo: "/logos/zendesk.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "6 months free for startups",
    description: "Zendesk offers 6 months free on their Suite plan for eligible startups. Customer service software with ticketing, chat, and knowledge base.",
    value: "6 months free",
    steps: "Apply at zendesk.com/startups\nMeet eligibility requirements (under 80 employees, funded)\nGet 6 months of Zendesk Suite free",
    url: "https://www.zendesk.com/campaign/startups/",
    featured: false,
  },
  {
    slug: "hubspot-startups",
    name: "HubSpot for Startups",
    logo: "/logos/hubspot.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Up to 90% off for startups",
    description: "HubSpot offers up to 90% off for eligible startups through partner programs. CRM, marketing, sales, and service tools in one platform.",
    value: "Up to 90% off",
    steps: "Apply at hubspot.com/startups\nVerify through a partner VC or accelerator\nGet discounted access to HubSpot suite",
    url: "https://www.hubspot.com/startups",
    featured: true,
  },
  {
    slug: "mailchimp",
    name: "Mailchimp",
    logo: "/logos/mailchimp.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Free plan for up to 500 contacts",
    description: "Mailchimp offers a free plan with up to 500 contacts and 1,000 email sends per month. Email marketing with templates and automation.",
    value: "Free tier",
    steps: "Sign up at mailchimp.com\nImport your contacts\nCreate and send email campaigns",
    url: "https://mailchimp.com/pricing/",
    featured: false,
  },
  {
    slug: "sendgrid",
    name: "SendGrid",
    logo: "/logos/sendgrid.svg",
    category: "SaaS",
    audiences: ["Startups", "Opensource"],
    tagline: "Free tier with 100 emails/day",
    description: "SendGrid by Twilio offers a free tier with 100 emails per day. Transactional and marketing email delivery with API and SMTP.",
    value: "Free tier",
    steps: "Sign up at sendgrid.com\nVerify your sender identity\nIntegrate via API or SMTP relay",
    url: "https://sendgrid.com/pricing/",
    featured: false,
  },
  {
    slug: "twilio-startups",
    name: "Twilio",
    logo: "/logos/twilio.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Credits for startups via partner programs",
    description: "Twilio offers credits through various startup and accelerator programs. Communication APIs for SMS, voice, video, and email.",
    value: "Startup credits",
    steps: "Apply through a Twilio startup partner\nGet approved for API credits\nIntegrate Twilio APIs into your product",
    url: "https://www.twilio.com/en-us/startups",
    featured: false,
  },
  {
    slug: "auth0-startups",
    name: "Auth0",
    logo: "/logos/auth0.svg",
    category: "SaaS",
    audiences: ["Startups", "Opensource"],
    tagline: "Free tier with 7,500 active users",
    description: "Auth0 offers a free tier with up to 7,500 monthly active users. Authentication and authorization platform with social login, MFA, and SSO.",
    value: "Free tier",
    steps: "Sign up at auth0.com\nCreate your first application\nIntegrate Auth0 SDK for authentication",
    url: "https://auth0.com/pricing",
    featured: false,
  },
  {
    slug: "algolia-startups",
    name: "Algolia",
    logo: "/logos/algolia.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "$10K in credits for startups",
    description: "Algolia offers $10K in credits for qualifying startups through their startup program. Search and discovery APIs with real-time indexing.",
    value: "$10,000 credits",
    steps: "Apply at algolia.com/startups\nDescribe your startup and search needs\nGet approved for $10K in credits",
    url: "https://www.algolia.com/startups/",
    featured: false,
  },
  {
    slug: "segment-startups",
    name: "Segment",
    logo: "/logos/segment.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Free Startup plan for early companies",
    description: "Segment offers a startup plan with free access to customer data platform. Collect, clean, and control customer data from one API.",
    value: "$50K credits",
    steps: "Apply at segment.com/startups\nConnect your data sources\nRoute customer data to your analytics tools",
    url: "https://segment.com/startup/",
    featured: false,
  },
  {
    slug: "amplitude-startups",
    name: "Amplitude",
    logo: "/logos/amplitude.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Free Scholarship plan for startups",
    description: "Amplitude offers a Scholarship plan for early-stage startups. Product analytics with up to 10M events and unlimited features.",
    value: "$36K/year",
    steps: "Apply at amplitude.com/startups\nMeet eligibility criteria\nGet free Growth plan for one year",
    url: "https://amplitude.com/startups",
    featured: false,
  },
  {
    slug: "loom-startups",
    name: "Loom",
    logo: "/logos/loom.svg",
    category: "SaaS",
    audiences: ["Startups"],
    tagline: "Free Starter plan for async video",
    description: "Loom provides a free Starter plan with 25 videos and 5 min max length. Record screen, camera, and mic for async communication.",
    value: "Free tier",
    steps: "Sign up at loom.com\nInstall browser extension or desktop app\nStart recording and sharing video messages",
    url: "https://www.loom.com/pricing",
    featured: false,
  },

  // ===== DESIGN (10) =====
  {
    slug: "canva-education",
    name: "Canva for Education",
    logo: "/logos/canva.svg",
    category: "Design",
    audiences: ["Students"],
    tagline: "Free Canva Pro for students and teachers",
    description: "Canva for Education gives students and teachers free access to Premium features including templates, stock photos, and brand kits.",
    value: "$120/year",
    steps: "Go to canva.com/education\nVerify your student or teacher status\nGet free Premium features activated",
    url: "https://www.canva.com/education/",
    featured: true,
  },
  {
    slug: "sketch-students",
    name: "Sketch",
    logo: "/logos/sketch.svg",
    category: "Design",
    audiences: ["Students"],
    tagline: "Free license for students",
    description: "Sketch offers free educational licenses for students studying design. Professional vector design tool for macOS.",
    value: "$120/year",
    steps: "Go to sketch.com/education\nApply with your .edu email\nReceive free educational license",
    url: "https://www.sketch.com/education/",
    featured: false,
  },
  {
    slug: "invision",
    name: "InVision",
    logo: "/logos/invision.svg",
    category: "Design",
    audiences: ["Students"],
    tagline: "Free prototyping for students",
    description: "InVision offers free access to its design collaboration and prototyping platform for students. Create interactive prototypes and design systems.",
    value: "Free tier",
    steps: "Sign up at invisionapp.com\nApply for student plan with .edu email\nStart creating prototypes",
    url: "https://www.invisionapp.com/plans",
    featured: false,
  },
  {
    slug: "framer",
    name: "Framer",
    logo: "/logos/framer.svg",
    category: "Design",
    audiences: ["Students", "Startups"],
    tagline: "Free plan for personal sites",
    description: "Framer offers a free plan with 1 published site, 1,000 visitors, and CMS. Build responsive websites with a visual editor and AI.",
    value: "Free tier",
    steps: "Sign up at framer.com\nDesign your site with the visual editor\nPublish for free on a framer.site domain",
    url: "https://www.framer.com/pricing/",
    featured: false,
  },
  {
    slug: "webflow-students",
    name: "Webflow",
    logo: "/logos/webflow.svg",
    category: "Design",
    audiences: ["Students"],
    tagline: "Free plan + student discount",
    description: "Webflow offers a free Starter plan and student discounts on paid plans. Visual web development platform with CMS and hosting.",
    value: "Free tier",
    steps: "Sign up at webflow.com\nBuild your site with the visual editor\nPublish on webflow.io for free",
    url: "https://webflow.com/pricing",
    featured: false,
  },
  {
    slug: "zeplin-education",
    name: "Zeplin",
    logo: "/logos/zeplin.svg",
    category: "Design",
    audiences: ["Students"],
    tagline: "Free plan for design handoff",
    description: "Zeplin offers a free plan for 1 project. Design-to-development handoff tool with specs, assets, and code snippets.",
    value: "Free tier",
    steps: "Sign up at zeplin.io\nUpload designs from Figma, Sketch, or XD\nShare specs and assets with developers",
    url: "https://zeplin.io/pricing",
    featured: false,
  },
  {
    slug: "marvel-app",
    name: "Marvel",
    logo: "/logos/marvel.svg",
    category: "Design",
    audiences: ["Students"],
    tagline: "Free plan for prototyping",
    description: "Marvel offers a free plan with 1 project. Design, prototype, and test user interfaces without code.",
    value: "Free tier",
    steps: "Sign up at marvelapp.com\nCreate a design or import from Sketch\nBuild interactive prototypes",
    url: "https://marvelapp.com/pricing/",
    featured: false,
  },
  {
    slug: "protopie",
    name: "ProtoPie",
    logo: "/logos/protopie.svg",
    category: "Design",
    audiences: ["Students"],
    tagline: "Free educational license for students",
    description: "ProtoPie offers free educational licenses for students. Create advanced interactive prototypes with sensors and variables.",
    value: "$156/year",
    steps: "Go to protopie.io/education\nApply with your .edu email\nGet free educational license activated",
    url: "https://www.protopie.io/plans/education",
    featured: false,
  },
  {
    slug: "spline",
    name: "Spline",
    logo: "/logos/spline.svg",
    category: "Design",
    audiences: ["Students", "Opensource"],
    tagline: "Free 3D design tool for the web",
    description: "Spline offers a free plan for 3D web design. Create interactive 3D scenes, animations, and experiences for the browser.",
    value: "Free tier",
    steps: "Sign up at spline.design\nCreate a 3D scene\nExport or embed directly in your website",
    url: "https://spline.design/pricing",
    featured: false,
  },
  {
    slug: "adobe-creative-cloud-students",
    name: "Adobe Creative Cloud",
    logo: "/logos/adobe.svg",
    category: "Design",
    audiences: ["Students"],
    tagline: "60% student discount on all apps",
    description: "Adobe offers 60% off Creative Cloud All Apps for students and teachers. Access Photoshop, Illustrator, Premiere Pro, and 20+ apps.",
    value: "60% off ($240/year savings)",
    steps: "Go to adobe.com/creativecloud/plans\nSelect the Students & Teachers plan\nVerify your student status via SheerID",
    url: "https://www.adobe.com/creativecloud/buy/students.html",
    featured: true,
  },

  // ===== LEARNING (10) =====
  {
    slug: "educative",
    name: "Educative.io",
    logo: "/logos/educative.svg",
    category: "Learning",
    audiences: ["Students"],
    tagline: "Free access for GitHub Education students",
    description: "Educative offers 6 months of free access to all courses through the GitHub Student Developer Pack. Interactive coding courses for developers.",
    value: "$200+ value",
    steps: "Get GitHub Student Developer Pack\nRedeem Educative access from partner offers\nStart learning with interactive courses",
    url: "https://www.educative.io/github-students",
    featured: false,
  },
  {
    slug: "pluralsight-students",
    name: "Pluralsight",
    logo: "/logos/pluralsight.svg",
    category: "Learning",
    audiences: ["Students"],
    tagline: "Free access to tech courses for students",
    description: "Pluralsight offers free access to its technology skills platform for students. Courses in development, IT, data, and cybersecurity.",
    value: "$300/year",
    steps: "Visit pluralsight.com\nApply for student free access\nStart learning with guided paths",
    url: "https://www.pluralsight.com/product/skills/individuals",
    featured: false,
  },
  {
    slug: "datacamp-students",
    name: "DataCamp",
    logo: "/logos/datacamp.svg",
    category: "Learning",
    audiences: ["Students"],
    tagline: "Free access for students via GitHub Education",
    description: "DataCamp offers 3 months free access through GitHub Student Developer Pack. Learn data science, analytics, and AI with hands-on exercises.",
    value: "$150 value",
    steps: "Get GitHub Student Developer Pack\nRedeem DataCamp access from partner offers\nComplete courses and earn certificates",
    url: "https://www.datacamp.com/github-students",
    featured: false,
  },
  {
    slug: "codecademy-students",
    name: "Codecademy",
    logo: "/logos/codecademy.svg",
    category: "Learning",
    audiences: ["Students"],
    tagline: "Free basic courses and student discounts",
    description: "Codecademy offers free basic courses and student discounts on Pro plans. Interactive coding lessons in Python, JavaScript, SQL, and more.",
    value: "35% off Pro",
    steps: "Sign up at codecademy.com\nExplore free courses or apply for student discount\nLearn interactively with hands-on exercises",
    url: "https://www.codecademy.com/student-center",
    featured: false,
  },
  {
    slug: "udemy-student",
    name: "Udemy",
    logo: "/logos/udemy.svg",
    category: "Learning",
    audiences: ["Students"],
    tagline: "Frequent sales and discounts on courses",
    description: "Udemy regularly offers courses for as low as $9.99 during sales. 200K+ courses across development, business, design, and more.",
    value: "Courses from $9.99",
    steps: "Sign up at udemy.com\nBrowse courses in your area of interest\nPurchase during frequent sales for best prices",
    url: "https://www.udemy.com/",
    featured: false,
  },
  {
    slug: "linkedin-learning",
    name: "LinkedIn Learning",
    logo: "/logos/linkedin.svg",
    category: "Learning",
    audiences: ["Students"],
    tagline: "Free through many university libraries",
    description: "LinkedIn Learning is available free through many university and public library subscriptions. 16K+ courses in business, tech, and creative skills.",
    value: "Free via library",
    steps: "Check if your university provides LinkedIn Learning\nLog in with your university credentials\nAccess all courses for free",
    url: "https://learning.linkedin.com/",
    featured: false,
  },
  {
    slug: "freecodecamp",
    name: "freeCodeCamp",
    logo: "/logos/freecodecamp.svg",
    category: "Learning",
    audiences: ["Students", "Opensource"],
    tagline: "100% free coding curriculum",
    description: "freeCodeCamp is a free, open source coding curriculum covering web dev, data science, and machine learning. Earn certifications by building projects.",
    value: "Free",
    steps: "Go to freecodecamp.org\nCreate an account\nStart with responsive web design certification",
    url: "https://www.freecodecamp.org/",
    featured: false,
  },
  {
    slug: "edx-students",
    name: "edX",
    logo: "/logos/edx.svg",
    category: "Learning",
    audiences: ["Students"],
    tagline: "Free audit access to university courses",
    description: "edX offers free audit access to courses from MIT, Harvard, and other top universities. Pay only for verified certificates.",
    value: "Free audit",
    steps: "Sign up at edx.org\nBrowse courses from top universities\nEnroll for free in audit mode",
    url: "https://www.edx.org/",
    featured: false,
  },
  {
    slug: "brilliant",
    name: "Brilliant",
    logo: "/logos/brilliant.svg",
    category: "Learning",
    audiences: ["Students"],
    tagline: "Interactive STEM learning platform",
    description: "Brilliant offers interactive courses in math, science, and CS. Free tier with limited daily problems, student discounts on Premium.",
    value: "Free tier + student discount",
    steps: "Sign up at brilliant.org\nExplore free daily problems\nUpgrade to Premium with student discount",
    url: "https://brilliant.org/premium/",
    featured: false,
  },
  {
    slug: "github-learning-lab",
    name: "GitHub Skills",
    logo: "/logos/github.svg",
    category: "Learning",
    audiences: ["Students", "Opensource"],
    tagline: "Free interactive Git and GitHub courses",
    description: "GitHub Skills offers free interactive courses to learn Git, GitHub, and developer workflows. Practice directly in GitHub repositories.",
    value: "Free",
    steps: "Go to skills.github.com\nChoose a course like Introduction to GitHub\nFollow step-by-step exercises in your own repo",
    url: "https://skills.github.com/",
    featured: false,
  },

  // ===== ENTERTAINMENT (10) =====
  {
    slug: "apple-music-student",
    name: "Apple Music Student",
    logo: "/logos/apple.svg",
    category: "Entertainment",
    audiences: ["Students"],
    tagline: "50% off Apple Music for students",
    description: "Apple Music Student plan is $5.99/month, half the regular price. Includes Apple TV+ and full Apple Music catalog.",
    value: "$60/year savings",
    steps: "Open Apple Music app or music.apple.com\nSelect the Student plan\nVerify student status via UNiDAYS",
    url: "https://support.apple.com/en-us/108943",
    featured: false,
  },
  {
    slug: "discord-nitro",
    name: "Discord Nitro",
    logo: "/logos/discord.svg",
    category: "Entertainment",
    audiences: ["Students"],
    tagline: "Occasional student promotions on Nitro",
    description: "Discord occasionally offers promotional Nitro deals for students. Nitro includes custom emoji, bigger uploads, HD streaming, and server boosts.",
    value: "Promotional pricing",
    steps: "Check Discord's current promotions\nSign up or upgrade during student deals\nEnjoy Nitro features like HD streaming",
    url: "https://discord.com/nitro",
    featured: false,
  },
  {
    slug: "notion-calendar",
    name: "Notion Calendar",
    logo: "/logos/notion.svg",
    category: "Entertainment",
    audiences: ["Students"],
    tagline: "Free calendar app for students",
    description: "Notion Calendar (formerly Cron) is free for everyone. Time management with Google Calendar integration and scheduling.",
    value: "Free",
    steps: "Download Notion Calendar\nConnect your Google Calendar\nStart scheduling with a clean interface",
    url: "https://www.notion.so/product/calendar",
    featured: false,
  },
  {
    slug: "headspace-students",
    name: "Headspace",
    logo: "/logos/headspace.svg",
    category: "Entertainment",
    audiences: ["Students"],
    tagline: "Student discount on meditation app",
    description: "Headspace offers student discounts on its meditation and mindfulness app. Guided meditations, sleep content, and focus exercises.",
    value: "$49.99/year (student)",
    steps: "Go to headspace.com/studentplan\nVerify student status\nGet discounted annual subscription",
    url: "https://www.headspace.com/studentplan",
    featured: false,
  },
  {
    slug: "calm-students",
    name: "Calm",
    logo: "/logos/calm.svg",
    category: "Entertainment",
    audiences: ["Students"],
    tagline: "Student pricing on wellness app",
    description: "Calm offers student discounts on its wellness app. Meditation, sleep stories, music, and relaxation content.",
    value: "Student discount",
    steps: "Visit calm.com\nLook for student pricing option\nVerify and subscribe at reduced rate",
    url: "https://www.calm.com/",
    featured: false,
  },
  {
    slug: "duolingo-plus",
    name: "Duolingo",
    logo: "/logos/duolingo.svg",
    category: "Entertainment",
    audiences: ["Students"],
    tagline: "Free language learning platform",
    description: "Duolingo offers free language courses in 40+ languages. Gamified lessons with streaks, leaderboards, and progress tracking.",
    value: "Free",
    steps: "Download Duolingo app or visit duolingo.com\nChoose a language to learn\nComplete daily lessons to build streaks",
    url: "https://www.duolingo.com/",
    featured: false,
  },
  {
    slug: "youtube-premium-student",
    name: "YouTube Premium Student",
    logo: "/logos/youtube.svg",
    category: "Entertainment",
    audiences: ["Students"],
    tagline: "50% off YouTube Premium for students",
    description: "YouTube Premium Student plan is $7.99/month instead of $13.99. Ad-free videos, YouTube Music, background play, and downloads.",
    value: "$72/year savings",
    steps: "Go to youtube.com/premium\nSelect the Student plan\nVerify student status via SheerID",
    url: "https://www.youtube.com/premium",
    featured: false,
  },
  {
    slug: "amazon-prime-student",
    name: "Amazon Prime Student",
    logo: "/logos/amazon.svg",
    category: "Entertainment",
    audiences: ["Students"],
    tagline: "50% off Prime + 6 months free trial",
    description: "Amazon Prime Student costs $7.49/month (half price) with a 6-month free trial. Includes free shipping, Prime Video, Prime Gaming, and more.",
    value: "$72/year savings",
    steps: "Go to amazon.com/joinstudent\nSign up with your .edu email\nEnjoy 6 months free then 50% off",
    url: "https://www.amazon.com/amazonprime?planOptimizationId=WLPStudentMonthlyElig498",
    featured: true,
  },
  {
    slug: "github-copilot-chat",
    name: "GitHub Copilot Chat",
    logo: "/logos/copilot.svg",
    category: "AI",
    audiences: ["Students", "Opensource"],
    tagline: "Free AI chat for coding questions",
    description: "GitHub Copilot Chat is included free for students and OSS maintainers. Ask coding questions, generate code, and debug directly in your IDE.",
    value: "Free with Copilot",
    steps: "Verify student status on GitHub Education\nEnable Copilot in GitHub settings\nOpen Copilot Chat panel in VS Code or JetBrains",
    url: "https://github.com/features/copilot",
    featured: false,
  },
  {
    slug: "microsoft-365-education",
    name: "Microsoft 365 Education",
    logo: "/logos/microsoft.svg",
    category: "SaaS",
    audiences: ["Students"],
    tagline: "Free Office 365 for students",
    description: "Microsoft provides Office 365 Education free for students and educators. Includes Word, Excel, PowerPoint, OneNote, Teams, and 1 TB OneDrive.",
    value: "$70/year",
    steps: "Go to microsoft.com/education\nEnter your school email address\nGet instant access to Office 365 online",
    url: "https://www.microsoft.com/en-us/education/products/office",
    featured: true,
  },
];

async function getExistingDeals(): Promise<Set<string>> {
  const slugs = new Set<string>();
  let hasMore = true;
  let startCursor: string | undefined;

  while (hasMore) {
    const url = `https://api.notion.com/v1/databases/${databaseId}/query`;
    const body: any = { page_size: 100 };
    if (startCursor) body.start_cursor = startCursor;

    const res = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.NOTION_TOKEN}`,
        "Notion-Version": "2022-06-28",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });
    const response: any = await res.json();

    for (const page of response.results || []) {
      const slugProp = page.properties?.Slug?.rich_text;
      if (slugProp && slugProp.length > 0) {
        slugs.add(slugProp[0].plain_text);
      }
    }

    hasMore = response.has_more ?? false;
    startCursor = response.next_cursor ?? undefined;
  }

  return slugs;
}

async function importDeals() {
  console.log("Fetching existing deals...");
  const existingSlugs = await getExistingDeals();
  console.log(`Found ${existingSlugs.size} existing deals.`);

  const toImport = newDeals.filter((d) => !existingSlugs.has(d.slug));
  console.log(`Will import ${toImport.length} new deals (${newDeals.length - toImport.length} skipped as duplicates).`);

  let imported = 0;
  let failed = 0;

  for (const deal of toImport) {
    try {
      await notionCreatePage({
        parent: { database_id: databaseId },
        properties: {
          Name: { title: [{ text: { content: deal.name } }] },
          Slug: { rich_text: [{ text: { content: deal.slug } }] },
          Logo: { rich_text: [{ text: { content: deal.logo } }] },
          Category: { select: { name: deal.category } },
          Audiences: {
            multi_select: deal.audiences.map((a: string) => ({ name: a })),
          },
          Tagline: { rich_text: [{ text: { content: deal.tagline } }] },
          Description: {
            rich_text: [{ text: { content: deal.description } }],
          },
          Value: { rich_text: [{ text: { content: deal.value } }] },
          Steps: { rich_text: [{ text: { content: deal.steps } }] },
          URL: { url: deal.url },
          Featured: { checkbox: deal.featured },
        },
      });
      imported++;
      console.log(`  [${imported}/${toImport.length}] + ${deal.name}`);
    } catch (err: any) {
      failed++;
      console.error(`  FAILED: ${deal.name} — ${err.message}`);
    }

    // Rate limit: Notion allows ~3 requests/sec
    if (imported % 3 === 0) {
      await new Promise((r) => setTimeout(r, 350));
    }
  }

  console.log(`\nDone! Imported: ${imported}, Failed: ${failed}`);
}

importDeals().catch(console.error);
